### ISSUE TITLE
Strip away extra keys in spec coercion with EDN & Transit

### ISSUE THREAD

**Issue by ikitommi** [metosin/reitit#317]
Currently, extra keys are only stripped for JSON. This is not good.

**Comment by joefromct** [comment]
I never noticed this as i was mostly using json...

Is there a work around for this for the time being, apart from going back to Schema?   

Note, maybe like [this](https://github.com/metosin/malli/issues/31) discussion with malli is relevant... albeit decided for us with `reitit.coercion.spec` needing to be plug-able with `reitit.coercion.schema` ?

> Schema has closed maps, Spec has open maps. Which one should malli default to? Controlled via :map property, which would be (depending on the default) either :closed or :open.

Thank you for reitit and everything.

**Comment by joefromct** [comment]
FYI, spoke to ikitommi in slack chat and he mentioned this:

> that should be fixed in 0.4.0

**Comment by ikitommi** [comment]
https://github.com/metosin/reitit/blob/master/CHANGELOG.md#reitit-spec

**Comment by ikitommi** [comment]
Yes, this should be fixed and tests to verify that: 

https://github.com/metosin/reitit/blob/master/test/cljc/reitit/ring_coercion_test.cljc

**Comment by Yaser-Amiri** [comment]
I think this is still a problem!
I'm using `[metosin/reitit "0.5.13"]` and you can see that the 'blah' doesn't remove from the result:

```
(require '[reitit.ring.coercion :as coercion])
(require '[reitit.coercion.schema])
(require '[reitit.ring :as ring])
(require '[clojure.spec.alpha :as s])

(s/def ::total int?)
(s/def ::result (s/keys :req-un [::total]))

(def app
  (ring/ring-handler
    (ring/router
      ["/api"
       ["/plus/" {:name ::plus
                  :post {:coercion reitit.coercion.spec/coercion
                         :responses {200 {:body ::result}}
                         :handler (fn [_] {:status 200 :body {:total 100 :blah 200}})}}]]
      {:data {:middleware [coercion/coerce-exceptions-middleware
                           coercion/coerce-request-middleware
                           coercion/coerce-response-middleware]}})))


(app {:request-method :post :uri "/api/plus/"}) ;; {:status 200, :body {:total 100, :blah 200}}
```
